/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StationStationIdIndexRouteImport } from './routes/station.$stationId.index'
import { Route as StationStationIdMapRouteImport } from './routes/station.$stationId.map'

const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StationStationIdIndexRoute = StationStationIdIndexRouteImport.update({
  id: '/station/$stationId/',
  path: '/station/$stationId/',
  getParentRoute: () => rootRouteImport,
} as any)
const StationStationIdMapRoute = StationStationIdMapRouteImport.update({
  id: '/station/$stationId/map',
  path: '/station/$stationId/map',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/feedback': typeof FeedbackRoute
  '/login': typeof LoginRoute
  '/safety': typeof SafetyRoute
  '/station/$stationId/map': typeof StationStationIdMapRoute
  '/station/$stationId/': typeof StationStationIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/feedback': typeof FeedbackRoute
  '/login': typeof LoginRoute
  '/safety': typeof SafetyRoute
  '/station/$stationId/map': typeof StationStationIdMapRoute
  '/station/$stationId': typeof StationStationIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/feedback': typeof FeedbackRoute
  '/login': typeof LoginRoute
  '/safety': typeof SafetyRoute
  '/station/$stationId/map': typeof StationStationIdMapRoute
  '/station/$stationId/': typeof StationStationIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/feedback'
    | '/login'
    | '/safety'
    | '/station/$stationId/map'
    | '/station/$stationId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/feedback'
    | '/login'
    | '/safety'
    | '/station/$stationId/map'
    | '/station/$stationId'
  id:
    | '__root__'
    | '/'
    | '/feedback'
    | '/login'
    | '/safety'
    | '/station/$stationId/map'
    | '/station/$stationId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FeedbackRoute: typeof FeedbackRoute
  LoginRoute: typeof LoginRoute
  SafetyRoute: typeof SafetyRoute
  StationStationIdMapRoute: typeof StationStationIdMapRoute
  StationStationIdIndexRoute: typeof StationStationIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/station/$stationId/': {
      id: '/station/$stationId/'
      path: '/station/$stationId'
      fullPath: '/station/$stationId/'
      preLoaderRoute: typeof StationStationIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/station/$stationId/map': {
      id: '/station/$stationId/map'
      path: '/station/$stationId/map'
      fullPath: '/station/$stationId/map'
      preLoaderRoute: typeof StationStationIdMapRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FeedbackRoute: FeedbackRoute,
  LoginRoute: LoginRoute,
  SafetyRoute: SafetyRoute,
  StationStationIdMapRoute: StationStationIdMapRoute,
  StationStationIdIndexRoute: StationStationIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
